### ISSUE TITLE
Shinyappsio error: Error fetching sass (0.4.0.9000) source. unable to satisfy package: sass (0.4.0.9000)

### ISSUE THREAD

**Issue by giannianfuso** [Drexel-UHC/shinyUHC#5]
I have been working on a Shiny app and was trying to publish it to my own shinyapps.io account (since I am still testing it). I get the following error message when publishing:

> Error: Unhandled Exception: Child Task 1150582039 failed: Error building image: Error fetching sass (0.4.0.9000) source. <CRANPackageSource repo='http://cran.rstudio.org'> unable to satisfy package: sass (0.4.0.9000)
Execution halted
[ShinyApp - Copy.zip](https://github.com/Drexel-UHC/shinyUHC/files/8662034/ShinyApp.-.Copy.zip)

**Comment by rl627** [comment]
The issue is the you setwd() call. When shinyApp() is called it will assume that the working directory is the root directory where app.R is located. So when you deploy to Shinyappsio it starts a ./app.R and tries to go to `setwd("C:/Users/ga437/OneDrive - Drexel University/Documents/Congressional-Districts/ShinyApp")` which doesn't exist in the virtual environemnt.

After you remove setwd() and deploy it shoudl work. See this version where i deployed  (after commenting out everything in your server because I don't have access to the data):   https://drexel-uhc.shinyapps.io/ShinyAppGiani/

**Comment by giannianfuso** [comment]
Thanks Ran! Looks like it got further along this time but still ended up failing with the same message:

> Error: Unhandled Exception: Child Task 1151864989 failed: Error building image: Error fetching sass (0.4.0.9000) source. <CRANPackageSource repo='http://cran.rstudio.org'> unable to satisfy package: sass (0.4.0.9000)
Execution halted

**Comment by rl627** [comment]
this is likely a dependency issue (I'm guessing with shiny or sasss package). 


I attached a file where I have implemented project-specific dependencies management ( **see this discussion #8 for an intro to dependency management**). It includes a file called renv.lock (this contains all the packages and versions I am using) and all the packages used installed locally. Try deploying **this app** to see if it works; this way we can make sure its not a dependency issue cause the error. 
 
- open "shinyAppGiana.rproj"
- try run app
- try deploy

**Comment by giannianfuso** [comment]
Thanks. I did not proceed with trying to deploy yet because nothing is showing in my "Lockfile" column:

![image](https://user-images.githubusercontent.com/29405605/168098543-dfdbe932-628a-4d85-b17c-451e8aac1a29.png)

**Comment by rl627** [comment]
weird! 😕 

Lets do a quick zoom meeting to debug this. Afternoon today works okay or tomorrow morning works for me

**Comment by giannianfuso** [comment]
Ran assisted me in getting the renv package set up to make sure all of my packages were using the correct versions
